GET http://localhost:3001/api/diagnoses

###
GET http://localhost:3001/api/patients

###
GET http://localhost:3001/api/patients/d27736ec-f723-11e9-8f0b-362b9e155667

###
GET http://localhost:3001/api/patients/d2773822-f723-11e9-8f0b-362b9e155667


###
POST http://localhost:3001/api/patients
Content-Type: application/json

{
    "name": "Eggward",
    "ssn": "123123123",
    "dateOfBirth": "12-2-2000",
    "gender": "male",
    "occupation": "headhunter"
}